### ISSUE TITLE
Add support for React Native 0.60

### ISSUE THREAD

**Issue by tikkichan4** [Jobeso/react-native-whatsapp-stickers#33]
## Discussion
React Native 0.60 now require linking native modules with cocoapods.
After i upgraded to 0.60, react-native-whatsapp-stickers would returns error with manual linking.

I tried to migrate it to Pod project, but swift files seems not worked with Pod project.

Any workaround for this ? it is really important to me. Thanks a lot

**Comment by Jobeso** [comment]
Cocoapods supports swift as well. The podfile that you need to create for that needs to include all the files, so swift files and the webp framework files. Maybe the Framework search path needs to change to find the snap sdk pod and most importantly the `use_frameworks!` flag needs to be set in podfile in order to work with swift pods. The missing support from RN of this was in the past the biggest problem but with RN 0.60 it might have changed, at least there is development around this. These are just hints, I don't know the solution to the problem.

**Comment by tikkichan4** [comment]
Thanks for your reply. i had tried to add `use_framework! `to pod before opening the issue. But it will returns the error:
![image](https://user-images.githubusercontent.com/18086245/63567615-e93e6680-c5a4-11e9-81af-9ce2d729f286.png)

And when i remove use_frameworks! and react-native-whatsapp-stickers, my project can be built successful, so i am sure this is the problem with using use_frameworks! on react native project.

**Comment by Jobeso** [comment]
v2.0.0 was just released which adds RN 0.60 support. Please reopen the issue if your problem still persists.
