### ISSUE TITLE
I can't send sticker on whatsup

### ISSUE THREAD

**Issue by techacorntest1** [Jobeso/react-native-whatsapp-stickers#6]
i got this Toast in Android when i send it:
There's a problem with this sticker pack and it can'be added to WhatsApp.

**Comment by Jobeso** [comment]
Hey,
this means that something is not right with your sticker pack or the configuration around it. When you create an issue, please follow the templates. So to be able to help you please post the content of `react-native info` (execute this in your terminal). Moreover, it's important to know about which platform we are talking and how your code looks because there is probably something wrong with it and the error message you postet is very generic.
Also look at the requires that WhatsApp has on sticker packs [here](https://github.com/WhatsApp/stickers/tree/master/Android#sticker-art-and-app-requirements) for android and [here](https://github.com/WhatsApp/stickers/tree/master/iOS#sticker-art-and-app-requirements) for iOS. Especially taking a look at your file sizes is important.

**Comment by techacorntest1** [comment]
I have add proper size of tray Icon ( 96 x 96 pixels) then it works fine.

**Comment by Jobeso** [comment]
@techacorntest1 
Glad to hear that it's working for you now.

I use custom stickers in my app and it's working great. Nice add-on for users.
